title: Harsh Vora
#logo: /assets/img/headshot_circle.png
description: Data Scientist
show_downloads: true
#theme: jekyll-theme-minimal
theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives
  - jekyll-gist
